"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faCode } from "@fortawesome/free-solid-svg-icons";
import "./globals.css";
import PageHeader from "./components/molecules/PageHeader";
import PageFooter from "./components/molecules/PageFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="./css/all.min.css" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
        flex flex-col min-h-screen bg-neutral-500`}
      >
        {/* Keep all pages confined within a header and footer layout */}
        <PageHeader/>
        <main className="flex-grow">{children}</main>
        <PageFooter/>
      </body>
    </html>
  );
}
